# Configuration Spring Boot pour TP_INF222 - Système de Gestion des Allergies
spring:
  application:
    name: tp222-allergies-management
  
  # Configuration base de données PostgreSQL (équivalent Flask SQLAlchemy)
  datasource:
    url: jdbc:postgresql://localhost:5432/tp222_allergies
    username: tp222_user
    password: tp222_password
    driver-class-name: org.postgresql.Driver
  
  # Configuration JPA/Hibernate (équivalent SQLAlchemy)
  jpa:
    hibernate:
      ddl-auto: update  # create-drop pour reset, update pour persist
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # Configuration des profils
  profiles:
    active: development

# Configuration Swagger/OpenAPI (équivalent Flask-RESTX)
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none

# Configuration du serveur
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

# Configuration des logs
logging:
  level:
    com.tp222.allergies: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configuration Actuator pour monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

---
# Profil de test (équivalent du config.py test)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true

---
# Profil Docker (équivalent docker-compose Flask)
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/tp222_allergies
    username: tp222_user
    password: tp222_password
